/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OrganizationUI;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import organization.organization;
import product.product;

/**
 *
 * @author pranavkapse
 */
public class AddNewItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewItemJPanel
     */
    JPanel CardContainer;
    organization userOrganization;
            
    public AddNewItemJPanel(JPanel CardContainer, organization userOrganization) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userOrganization = userOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemType = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtItemAvailibility = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblUserTitle = new javax.swing.JLabel();
        lblItemCost = new javax.swing.JLabel();
        btnBackcourse = new javax.swing.JButton();
        txtItemType1 = new javax.swing.JTextField();
        lblItemCost1 = new javax.swing.JLabel();
        txtItemCost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ItemType.setText("Item Type:");
        add(ItemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 40));

        lblItemName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemName.setText("Item Name:");
        add(lblItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 40));
        add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, 40));

        txtItemAvailibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemAvailibilityActionPerformed(evt);
            }
        });
        add(txtItemAvailibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 170, 40));

        btnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 80, 40));

        lblUserTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblUserTitle.setText("Add New Item here");
        add(lblUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 27));

        lblItemCost.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemCost.setText("Item Availibility:");
        add(lblItemCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 40));

        btnBackcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBackcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackcourseActionPerformed(evt);
            }
        });
        add(btnBackcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 40));

        txtItemType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemType1ActionPerformed(evt);
            }
        });
        add(txtItemType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 170, 40));

        lblItemCost1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemCost1.setText("Item Cost:");
        add(lblItemCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, 40));

        txtItemCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCostActionPerformed(evt);
            }
        });
        add(txtItemCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizationUI/org.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1420, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemAvailibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemAvailibilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemAvailibilityActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        product Product = new product();

        Product.setName(txtItemName.getText());
        Product.setType(txtItemType1.getText());

        try {
        int price = Integer.parseInt(txtItemCost.getText());
        int availability = Integer.parseInt(txtItemAvailibility.getText());

      
        if (price < 0 || availability < 0) {
        JOptionPane.showMessageDialog(this, "Please enter non-negative numbers for price and availability");
        return;
        }

        Product.setPrice(price);
        Product.setAvailibility(availability);
        } catch (NumberFormatException e) {
            
        JOptionPane.showMessageDialog(this, "Please enter only numbers in price and availability");
        return;
    }

        userOrganization.addProductToOrganization(Product);
        Product.setProductOrganization(userOrganization);

        JOptionPane.showMessageDialog(this, "Product added");

        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackcourseActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackcourseActionPerformed

    private void txtItemType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemType1ActionPerformed

    private void txtItemCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemType;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblItemCost;
    private javax.swing.JLabel lblItemCost1;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblUserTitle;
    private javax.swing.JTextField txtItemAvailibility;
    private javax.swing.JTextField txtItemCost;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemType1;
    // End of variables declaration//GEN-END:variables
}
