/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OrganizationUI;

import MainUserInterface.MainJFrame;
import deliveryPartner.deliveryPartnerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import organization.organization;



/**
 *
 * @author pranavkapse
 */

public class OrganisationLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdminJPanel
     */

    JPanel CardContainer;
    organization userOrganization;
    deliveryPartnerDirectory deliveryPartnerList;
    
    public OrganisationLandingJPanel(JPanel CardContainer, organization userOrganization, deliveryPartnerDirectory deliveryPartnerList) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userOrganization = userOrganization;
        this.deliveryPartnerList = deliveryPartnerList;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPendingOrders = new javax.swing.JButton();
        btnPreviousOrders = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewItems = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPendingOrders.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnPendingOrders.setText("Pending Orders");
        btnPendingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingOrdersActionPerformed(evt);
            }
        });
        add(btnPendingOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 140, 52));

        btnPreviousOrders.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnPreviousOrders.setText("Previous Orders");
        btnPreviousOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousOrdersActionPerformed(evt);
            }
        });
        add(btnPreviousOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 52));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Manage Items");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 192, 66));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Manage Orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 192, 66));

        btnViewItems.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnViewItems.setText("View Items");
        btnViewItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemsActionPerformed(evt);
            }
        });
        add(btnViewItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 140, 50));

        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizationUI/org.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1470, 980));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingOrdersActionPerformed
        // TODO add your handling code here:
        ViewPendingOrdersFirstJPanel viewPendingOrdersFirstJPanel = new ViewPendingOrdersFirstJPanel(CardContainer, userOrganization, deliveryPartnerList);
        CardContainer.add("ViewPendingOrdersFirstJPanel", viewPendingOrdersFirstJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_btnPendingOrdersActionPerformed

    private void btnPreviousOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousOrdersActionPerformed
        // TODO add your handling code here:
        ViewPreviousOrdersJPanel viewPreviousOrdersJPanel = new ViewPreviousOrdersJPanel(CardContainer, userOrganization);
        CardContainer.add("ViewPreviousOrdersJPanel", viewPreviousOrdersJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    
    }//GEN-LAST:event_btnPreviousOrdersActionPerformed

    private void btnViewItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemsActionPerformed
        // TODO add your handling code here:
        ViewItemsJPanel viewItemsJPanel = new ViewItemsJPanel(CardContainer, userOrganization);
        CardContainer.add("ViewItemsJPanel", viewItemsJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
       
    }//GEN-LAST:event_btnViewItemsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
        
       // MainJFrame mainFrame= new MainJFrame();
        //CardContainer.removeAll();
        //CardContainer.add(mainFrame);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPendingOrders;
    private javax.swing.JButton btnPreviousOrders;
    private javax.swing.JButton btnViewItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
