/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package OrganizationUI;


import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import order.order;
import organization.organization;

/**
 *
 * @author pranavkapse
 */
public class ViewPreviousOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudentRequestJPanel
     */
    
    JPanel CardContainer;
    organization userOrganization;
    
    public ViewPreviousOrdersJPanel(JPanel CardContainer, organization userOrganization) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userOrganization = userOrganization;
        populatePreviousOrders();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingOrdersPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreviousOrders = new javax.swing.JTable();
        btnBackcourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        pendingOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));
        pendingOrdersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPreviousOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer Name", "Total Cost", "Order Status"
            }
        ));
        jScrollPane1.setViewportView(tblPreviousOrders);

        pendingOrdersPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 630, 260));

        btnBackcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBackcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackcourseActionPerformed(evt);
            }
        });
        pendingOrdersPanel.add(btnBackcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 40));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Previous Orders");
        pendingOrdersPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizationUI/org.png"))); // NOI18N
        pendingOrdersPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1470, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendingOrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pendingOrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackcourseActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackcourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pendingOrdersPanel;
    private javax.swing.JTable tblPreviousOrders;
    // End of variables declaration//GEN-END:variables

    private void populatePreviousOrders() {
        
        DefaultTableModel model = (DefaultTableModel) tblPreviousOrders.getModel();
        model.setRowCount(0);
        
        ArrayList<order> pastOrderList = userOrganization.getCompletedOrders();
        
        for (order Order : pastOrderList){
            Object[] row = new Object[3];
            row[0] = Order.getCustomerProfile().getName();
            row[1] = Order.calculateOrderTotal(Order);
            row[2] = Order.getStatus();
            
            model.addRow(row);
            
        }
        
       
    }
        
}
