/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminUI;

import enterprise.enterprise;
import enterprise.enterpriseDirectory;
import java.awt.CardLayout;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import organization.organization;

/**
 *
 * @author kaush
 */
public class AdminmanageenterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminmanageJPanel
     */
    JPanel CardContainer;
    enterpriseDirectory enterpriseList;
            
    public AdminmanageenterpriseJPanel(JPanel CardContainer, enterpriseDirectory enterpriseList) {
        initComponents();
        this.CardContainer = CardContainer;
        this.enterpriseList = enterpriseList;
        
        populateEnterpriseTable();
    }

    AdminmanageenterpriseJPanel(Container CardContainer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnCreateEnterprise = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 410, 45));

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Enterprise Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);
        if (tblEnterprise.getColumnModel().getColumnCount() > 0) {
            tblEnterprise.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 180));

        btnRemove.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRemove.setText("Remove ");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 90, 50));

        btnCreateEnterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCreateEnterprise.setText("Create New Enterprise");
        btnCreateEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEnterpriseActionPerformed(evt);
            }
        });
        add(btnCreateEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, 60));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Create New Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 210, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 40));

        btnRefresh.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminUI/admin.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1470, 1040));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEnterpriseActionPerformed
        // TODO add your handling code here:
        AddEnterpriseJPanel addEnterpriseJPanel = new AddEnterpriseJPanel(CardContainer, enterpriseList);
        CardContainer.add("AddEnterpriseJPanel", addEnterpriseJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_btnCreateEnterpriseActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblEnterprise.getSelectedRow();
        enterprise selectedEnterprise = null;
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select the enterprise");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        int enterpriseID = (int) model.getValueAt(selectedRowIndex, 0);
        
        for (enterprise Enterprise : enterpriseList.getEnterpriseList()){
            if (Enterprise.getEnterpriseID() == enterpriseID){
                selectedEnterprise = Enterprise;
                break;
                }
        }
        
        ArrayList<organization> organizationList = selectedEnterprise.getOrganizationList();
        
        for (organization Org : organizationList){
            if (Org.getPendingOrders().size() > 0){
                JOptionPane.showMessageDialog(this, "This enterprise has some pending orders");
                return;
            }
        }
        
        enterpriseList.removeEnterprise(selectedEnterprise);
        
        JOptionPane.showMessageDialog(this, "Enterprise deleted");
        
        populateEnterpriseTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
        populateEnterpriseTable();
        
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateEnterprise;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnterprise;
    // End of variables declaration//GEN-END:variables

    private void populateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        model.setRowCount(0);

        for (enterprise Enterprise : enterpriseList.getEnterpriseList()){
            Object[] row = new Object[2];
            row[0] = Enterprise.getEnterpriseID();
            row[1] = Enterprise.getName();
            
            model.addRow(row);
            
        }
    }
}
