/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerUI;

import customer.customer;
import enterprise.enterpriseDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class CustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerJPanel
     */
    JPanel CardContainer;
    customer userCustomer;
    enterpriseDirectory enterpriseList;
    
    public CustomerJPanel(JPanel CardContainer, customer userCustomer, enterpriseDirectory enterpriseList) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userCustomer = userCustomer;
        this.enterpriseList = enterpriseList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btnneworder = new javax.swing.JButton();
        Btnviewporders = new javax.swing.JButton();
        Btneditpf = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btnneworder.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Btnneworder.setText("Place New Order");
        Btnneworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnneworderActionPerformed(evt);
            }
        });
        add(Btnneworder, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 184, 180, 50));

        Btnviewporders.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Btnviewporders.setText("View Previous Orders");
        Btnviewporders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewpordersActionPerformed(evt);
            }
        });
        add(Btnviewporders, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 184, -1, 50));

        Btneditpf.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Btneditpf.setText("Edit Profile");
        Btneditpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneditpfActionPerformed(evt);
            }
        });
        add(Btneditpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 183, 132, 51));

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 40));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel1.setText("Welcome to Online Order Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 110, -1, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizationUI/main5.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, -30, 2100, 940));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnneworderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnneworderActionPerformed
        // TODO add your handling code here:
        CustomerNewOrderJPanel customerneworderJPanel = new CustomerNewOrderJPanel(CardContainer, userCustomer, enterpriseList);
        CardContainer.add("CustomerNewOrderJPanel", customerneworderJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);

    }//GEN-LAST:event_BtnneworderActionPerformed

    private void BtnviewpordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewpordersActionPerformed
        // TODO add your handling code here:
        PreviousOrdersJPanel previousordersJPanel = new PreviousOrdersJPanel(CardContainer, userCustomer);
        CardContainer.add("PreviousOrdersJPanel",previousordersJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_BtnviewpordersActionPerformed

    private void BtneditpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneditpfActionPerformed
        // TODO add your handling code here:
        CustomerProfileJPanel customerprofileJPanel = new CustomerProfileJPanel(CardContainer, userCustomer);
        CardContainer.add("CustomerProfileJPanel", customerprofileJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_BtneditpfActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btneditpf;
    private javax.swing.JButton Btnneworder;
    private javax.swing.JButton Btnviewporders;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
