/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pranavkapse
 */
public class AboutUsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutUsJPanel
     */
    JPanel CardContainer;
    public AboutUsJPanel(JPanel CardContainer) {
        initComponents();
        this.CardContainer = CardContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        btnBackcourse = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("About Us:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Customer's Feedback:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 710, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome to our Order Management System, where convenience meets diversity, and your every need finds a home. We take pride in being your go-to \nonline destination, offering a seamless platform that brings together a rich variety of products, spanning retail, food, clothing, and electronics – all in one \nplace. At our core, we believe that shopping for what you need should be a straightforward and enjoyable experience. Our platform is not just a marketplace\nit's a friendly and user-centric space designed with simplicity in mind. We understand the value of your time and have crafted an environment where you \ncan effortlessly discover, purchase, and order a wide array of products. What sets us apart is our commitment to being your all-in-one solution. \nWhether you're in search of the latest fashion trends, essential groceries, or cutting-edge electronic gadgets, we've curated a collection that caters to your\n diverse needs. Consider us your virtual shopping haven, where convenience meets variety. Our platform is more than just a place to shop – it's a \ncommunity built on the principles of ease and efficiency. We've created an intuitive interface that allows you to navigate seamlessly, add products to your \ncart with a simple click, and complete your order hassle-free.\n\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1130, 190));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setText("Mission & Vision:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 710, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/kishor.jpeg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 260, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/kaushik.jpeg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 250, 280));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/pk.jpeg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 320, 280));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("This website serves as a comprehensive \ndestination, catering to all your product needs in \na seamless and efficient manner - Kishor Kashid");
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 790, 330, 90));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("The Online Order Management System\nhas consistently ensured timely delivery\nof all products - Kaushik Karanam");
        jScrollPane4.setViewportView(jTextArea4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, 270, 80));

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("The online order management system \nnot only prioritizes timely deliveries but \nalso places a strong emphasis on \nproduct quality.  - Pranav Kapse");
        jScrollPane5.setViewportView(jTextArea5);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 790, 290, 90));

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Welcome to our Order Management System, where convenience meets diversity, and your every need finds a home. We take pride in being your go-to \nonline destination, offering a seamless platform that brings together a rich variety of products, spanning retail, food, clothing, and electronics – all in \none place. At our core, we believe that shopping for what you need should be a straightforward and enjoyable experience. Our platform is not just a \nmarketplace it's a friendly and user-centric space designed with simplicity in mind. We understand the value of your time and have crafted an \nenvironment where you can effortlessly discover, purchase, and order a wide array of products. What sets us apart is our commitment to being your \nall-in-one solution. Whether you're in search of the latest fashion trends, essential groceries, or cutting-edge electronic gadgets, we've curated a \ncollection that caters to your diverse needs. Consider us your virtual shopping haven, where convenience meets variety. Our platform is more than \njust a place to shop – it's a community built on the principles of ease and efficiency. We've created an intuitive interface that allows you to navigate \nseamlessly, add products to your cart with a simple click, and complete your order hassle-free.\n\n");
        jScrollPane6.setViewportView(jTextArea6);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1100, 160));

        btnBackcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBackcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackcourseActionPerformed(evt);
            }
        });
        add(btnBackcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackcourseActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackcourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
