/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EnterpriseUI;

import enterprise.enterprise;
import java.awt.CardLayout;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import organization.organization;
import organization.organizationDirectory;

/**
 *
 * @author pranavkapse
 */
public class AddOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddOrganizationJPanel
     */
    JPanel CardContainer;
    enterprise userEnterprise;
    organizationDirectory globalOrganizationList;
    
    public AddOrganizationJPanel(JPanel CardContainer, enterprise userEnterprise, organizationDirectory globalOrganizationList) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userEnterprise = userEnterprise;
        this.globalOrganizationList = globalOrganizationList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemType = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblUserTitle = new javax.swing.JLabel();
        lblItemCost = new javax.swing.JLabel();
        btnBackcourse = new javax.swing.JButton();
        lblItemCost1 = new javax.swing.JLabel();
        lblItemCost2 = new javax.swing.JLabel();
        lblItemCost3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ItemType.setText("Email ID:");
        add(ItemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 40));

        lblItemName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemName.setText("Orgnization Name:");
        add(lblItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 40));

        btnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 80, 40));

        lblUserTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblUserTitle.setText("Add New Orgnization");
        add(lblUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, 27));

        lblItemCost.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemCost.setText("Address:");
        add(lblItemCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, 40));

        btnBackcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBackcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackcourseActionPerformed(evt);
            }
        });
        add(btnBackcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 40));

        lblItemCost1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemCost1.setText("Phone Number:");
        add(lblItemCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, 40));

        lblItemCost2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemCost2.setText("Password:");
        add(lblItemCost2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, 40));

        lblItemCost3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblItemCost3.setText("User Name:");
        add(lblItemCost3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, 40));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 210, 40));

        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 210, 40));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 210, 40));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 210, 40));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 210, 40));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnterpriseUI/skyline-1925943_1920.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -130, 1460, 1270));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        String username = txtUsername.getText();
        if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter username");
            return;
        }
        
        boolean isOrganizationUsernameUnique = globalOrganizationList.isOrganizationUsernameUnique(username);

        if (isOrganizationUsernameUnique == false){
            JOptionPane.showMessageDialog(null, "This username already exist");
            return;
        }

        organization Organization = new organization();

        Organization.setName(txtName.getText());
        Organization.setEmailID(txtEmail.getText());

        try {
            Integer.parseInt(txtPhoneNo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter only numbers in Phone Number");
            return;
        }
        
        Organization.setPhonenumber(txtPhoneNo.getText());

        Organization.setAddress(txtAddress.getText());

        Organization.setUsername(username);
        Organization.setEnterpriseProfile(userEnterprise);

        // Validate password
        String password = txtPassword.getText();
        if (isPasswordValid(password)) {
            password = hashedPassword(password);
            Organization.setPassword(password);
        } else {
            JOptionPane.showMessageDialog(this, "Password is not valid. It should contain at least one uppercase letter, one lowercase letter, one special character, one number, and be at least 8 characters long.");
            return;
        }

        userEnterprise.addOrganization(Organization);
        globalOrganizationList.addOrganization(Organization);

        JOptionPane.showMessageDialog(this, "Organization added Successfully!");
        
        txtName.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtPhoneNo.setText("");
        txtUsername.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackcourseActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackcourseActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemType;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblItemCost;
    private javax.swing.JLabel lblItemCost1;
    private javax.swing.JLabel lblItemCost2;
    private javax.swing.JLabel lblItemCost3;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblUserTitle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables


    private boolean isPasswordValid(String password) {
        // Use regex to enforce password complexity rules
        String passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=]).{8,}$";
        return password.matches(passwordRegex);
    }
    
    private String hashedPassword(String password) {
        try {
 
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(password.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }

        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}