/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EnterpriseUI;

import enterprise.enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import organization.organizationDirectory;

/**
 *
 * @author pranavkapse
 */
public class EnterpriseLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseLandingJPanel
     */
    JPanel CardContainer;
    enterprise userEnterprise;
    organizationDirectory globalOrganizationList;
    
    public EnterpriseLandingJPanel(JPanel CardContainer, enterprise userEnterprise, organizationDirectory organizationList) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userEnterprise = userEnterprise;
        this.globalOrganizationList = organizationList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddOrg = new javax.swing.JButton();
        btnRemoveOrg = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Manage Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 260, 38));

        btnAddOrg.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAddOrg.setText("Add Organization");
        btnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrgActionPerformed(evt);
            }
        });
        add(btnAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 60));

        btnRemoveOrg.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRemoveOrg.setText("View/Remove Organization");
        btnRemoveOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrgActionPerformed(evt);
            }
        });
        add(btnRemoveOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 220, 60));

        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnterpriseUI/skyline-1925943_1920.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1400, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrgActionPerformed
        // TODO add your handling code here:
        AddOrganizationJPanel addOrganizationJPanel = new AddOrganizationJPanel(CardContainer, userEnterprise, globalOrganizationList);
        CardContainer.add("AddOrganizationJPanel", addOrganizationJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_btnAddOrgActionPerformed

    private void btnRemoveOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrgActionPerformed
        // TODO add your handling code here:
        ViewOrRemoveOrganizationJPanel viewOrRemoveOrganizationJPanel = new ViewOrRemoveOrganizationJPanel(CardContainer, userEnterprise, globalOrganizationList);
        CardContainer.add("ViewOrRemoveOrganizationJPanel", viewOrRemoveOrganizationJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_btnRemoveOrgActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrg;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRemoveOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
