/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EnterpriseUI;

import enterprise.enterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import organization.organization;
import organization.organizationDirectory;

/**
 *
 * @author pranavkapse
 */
public class ViewOrRemoveOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrRemoveOrganizationJPanel
     */
    JPanel CardContainer;
    enterprise userEnterprise;
    organizationDirectory globalOrganizationList;
    //enterprise organizationList;
    public ViewOrRemoveOrganizationJPanel(JPanel CardContainer, enterprise userEnterprise, organizationDirectory globalOrganizationList) {
        initComponents();
       this.CardContainer = CardContainer;
       this.userEnterprise = userEnterprise;
       this.globalOrganizationList = globalOrganizationList;
      // this.organizationList = organizationList;
       
       populateOrganizationInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizationList = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnBackcourse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("View or Remove Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 342, -1));

        tblOrganizationList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Organization Name", "Address"
            }
        ));
        jScrollPane1.setViewportView(tblOrganizationList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 339));

        btnRemove.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRemove.setText("REMOVE");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 95, 42));

        btnBackcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBackcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackcourseActionPerformed(evt);
            }
        });
        add(btnBackcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EnterpriseUI/skyline-1925943_1920.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1440, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        /*
        int selectRowIndex = tblOrganizationList.getSelectedRow();
        
        if(selectRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to Remove Organization.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblOrganizationList.getModel();
        //String selectedOrganization;
         organization selectedOrganization = (organization) model.getValueAt(selectRowIndex, 0);
       // organization selectedOrganization = null;
        for (organization org : userEnterprise.getOrganizationList()) {
            
            if (org.getName().equals(selectedOrganization.getName())) {
                selectedOrganization = org;
                break;
            }
        }

        userEnterprise.removeOrganization(selectedOrganization);
        JOptionPane.showMessageDialog(this, "Organization removed Successfully!");
        
        populateOrganizationInfo();
        */
        
        int selectedRowIndex = tblOrganizationList.getSelectedRow();
        organization selectedOrganization = null;
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to Remove Organization.");
            return;
        }
        
        ArrayList<organization> OrganizationList = userEnterprise.getOrganizationList();
        
        DefaultTableModel model = (DefaultTableModel) tblOrganizationList.getModel();
        String OrganizationName = (String) model.getValueAt(selectedRowIndex, 1);
        
        for (organization Organization : OrganizationList){
            if (Organization.getName().equals(OrganizationName)){
                selectedOrganization = Organization;
                break;
                }
        }
        
        if (selectedOrganization.getPendingOrders().size() > 0){
            JOptionPane.showMessageDialog(this, "This organization has some pending orders");
            return;
        }
        
        userEnterprise.removeOrganization(selectedOrganization);
        globalOrganizationList.removeOrganization(selectedOrganization);
        JOptionPane.showMessageDialog(this, "Organization removed Successfully!");
        
        populateOrganizationInfo();

        
        
     
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackcourseActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackcourseActionPerformed

    private void populateOrganizationInfo() {
        
        DefaultTableModel model = (DefaultTableModel) tblOrganizationList.getModel();
         model.setRowCount(0);
       
       
       ArrayList<organization> organizationList = userEnterprise.getOrganizationList();
        
        for (organization Organization : organizationList){
            Object[] row = new Object[3];
            row[0] = Organization.getOrganizationID();
            row[1] = Organization.getName();
            row[2] = Organization.getAddress();
 
            model.addRow(row);
            
        }
        
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackcourse;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrganizationList;
    // End of variables declaration//GEN-END:variables
}
