/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DeliveryPartnerUI;

import deliveryPartner.deliveryPartner;
import enterprise.enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import organization.organization;

/**
 *
 * @author pranavkapse
 */
public class DeliveryPartnerLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryPartnerLandingJPanel
     */
    JPanel CardContainer;
    deliveryPartner userDeliveryPartner;
    public DeliveryPartnerLandingJPanel(JPanel CardContainer, deliveryPartner userDeliveryPartner) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userDeliveryPartner = userDeliveryPartner;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCompletedOrders = new javax.swing.JButton();
        btnPendingOrders = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Manage All the Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 290, 50));

        btnCompletedOrders.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCompletedOrders.setText("View Completed Orders");
        btnCompletedOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletedOrdersActionPerformed(evt);
            }
        });
        add(btnCompletedOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 230, 70));

        btnPendingOrders.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnPendingOrders.setText("View Pending Orders");
        btnPendingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingOrdersActionPerformed(evt);
            }
        });
        add(btnPendingOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 200, 70));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeliveryPartnerUI/delivery.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1450, 970));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompletedOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedOrdersActionPerformed
        // TODO add your handling code here:
        ViewCompletedOrdersJPanel viewCompletedOrdersJPanel = new ViewCompletedOrdersJPanel(CardContainer, userDeliveryPartner);
        CardContainer.add("ViewCompletedOrdersJPanel", viewCompletedOrdersJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_btnCompletedOrdersActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnPendingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingOrdersActionPerformed
        // TODO add your handling code here:
        ViewPendingOrdersJPanel viewPendingOrdersJPanel = new ViewPendingOrdersJPanel(CardContainer, userDeliveryPartner);
        CardContainer.add("ViewPendingOrdersJPanel", viewPendingOrdersJPanel);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.next(CardContainer);
    }//GEN-LAST:event_btnPendingOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompletedOrders;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPendingOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
