/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DeliveryPartnerUI;

import deliveryPartner.deliveryPartner;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import order.order;

/**
 *
 * @author pranavkapse
 */
public class ViewPendingOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPendingOrdersJPanel
     */
    JPanel CardContainer;
    deliveryPartner userDeliveryPartner;
    public ViewPendingOrdersJPanel( JPanel CardContainer, deliveryPartner userDeliveryPartner) {
        initComponents();
        this.CardContainer = CardContainer;
        this.userDeliveryPartner = userDeliveryPartner;
        
        populatePendingOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingOrders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBackcourse = new javax.swing.JButton();
        btnAcceptOrder1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPendingOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Customer Address", "Order ID", "Organization", "Order Total"
            }
        ));
        jScrollPane1.setViewportView(tblPendingOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 880, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Manage Pending Orders ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        btnBackcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/left-arrow (2).png"))); // NOI18N
        btnBackcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackcourseActionPerformed(evt);
            }
        });
        add(btnBackcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 40));

        btnAcceptOrder1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAcceptOrder1.setText("Accept Order");
        btnAcceptOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptOrder1ActionPerformed(evt);
            }
        });
        add(btnAcceptOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeliveryPartnerUI/delivery.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 1450, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackcourseActionPerformed
        // TODO add your handling code here:
        CardContainer.remove(this);
        CardLayout layout = (CardLayout) CardContainer.getLayout();
        layout.previous(CardContainer);
    }//GEN-LAST:event_btnBackcourseActionPerformed

    private void btnAcceptOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptOrder1ActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblPendingOrders.getSelectedRow();
        order selectedOrder = null;
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select the order");
            return;
        }
        
        ArrayList<order> pendingOrderList = userDeliveryPartner.getPendingOrders();
        
        DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();
        int orderID = (int) model.getValueAt(selectedRowIndex, 2);
        
        for (order Order : pendingOrderList){
            if (Order.getOrderID() == orderID){
                selectedOrder = Order;
                break;
                }
        }
        
        selectedOrder.setStatus("Ready for delivery");
        userDeliveryPartner.addCompletedOrder(selectedOrder);
        double revenue = userDeliveryPartner.getRevenue() + selectedOrder.calculateOrderTotal(selectedOrder) * userDeliveryPartner.getPercentShare() / 100;
        userDeliveryPartner.setRevenue(revenue);
        
        JOptionPane.showMessageDialog(this, "Order Accepted");
        
        populatePendingOrders();
        
        
    }//GEN-LAST:event_btnAcceptOrder1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptOrder1;
    private javax.swing.JButton btnBackcourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendingOrders;
    // End of variables declaration//GEN-END:variables

    private void populatePendingOrders() {
       
        DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();
        model.setRowCount(0);
        
        ArrayList<order> pendingOrderList = userDeliveryPartner.getPendingOrders();
        
        for(order Order : pendingOrderList){
            
            Object[] row = new Object[5];
            row[0] = Order.getCustomerProfile().getName();
            row[1] = Order.getCustomerProfile().getAddress();
            row[2] = Order.getOrderID();
            row[3] = Order.getOrganizationProfile().getName();
            row[4] = Order.calculateOrderTotal(Order);
            
            model.addRow(row);
        }
   
    }
}
